namespace Shiny.AiConversation;

/// <summary>
/// Represents a single chat message persisted in the message store.
/// </summary>
/// <param name="Id">Unique identifier for the message.</param>
/// <param name="Message">The text content of the message.</param>
/// <param name="Timestamp">When the message was sent or received.</param>
/// <param name="Direction">Whether the message was sent by the user or the AI.</param>
/// <param name="InputTokens">Tokens consumed by the model for the prompt that produced this AI message. Null for user messages or when the provider doesn't report usage.</param>
/// <param name="OutputTokens">Tokens generated by the model for this AI message. Null for user messages or when the provider doesn't report usage.</param>
/// <param name="TotalTokens">Total tokens billed for this AI message. Null for user messages or when the provider doesn't report usage.</param>
public record AiChatMessage(
    string Id,
    string Message,
    DateTimeOffset Timestamp,
    ChatMessageDirection Direction,
    long? InputTokens = null,
    long? OutputTokens = null,
    long? TotalTokens = null
);

/// <summary>
/// Indicates the origin of a chat message.
/// </summary>
public enum ChatMessageDirection
{
    /// <summary>The message was sent by the user.</summary>
    User,
    /// <summary>The message was generated by the AI.</summary>
    AI
}
