<Project>
    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

    <PropertyGroup>
        <Description>Shiny Speech - Cross-platform speech-to-text and text-to-speech for .NET MAUI</Description>
        <PackageTags>maui speech tts stt text-to-speech speech-to-text shiny</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)readme.md" Pack="true" PackagePath="\" />
    </ItemGroup>
</Project>
