<Project>
    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

    <PropertyGroup>
        <Description>Shiny Audio - Cross-platform audio capture and playback for .NET MAUI</Description>
        <PackageTags>maui audio recording playback microphone pcm shiny</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)readme.md" Pack="true" PackagePath="\" />
    </ItemGroup>
</Project>
